msm8960: Squashed fixes for O msm8960: fixes for N
* fixup of 4ed66e62279001cd62e5acec53f3e1cf5d64e77d for 8960
* port across a few constants from de4849cee04a23ae84da96487e344f75f93e5585
  to get 8960 building.

Change-Id: I98bbf5843d9b93ba1263e36a0ad64ea596cec244

msm8960: define HFP_ASM_RX_TX 24

Taken from hardware/qcom/audio-car/msm8960/hal/msm8969/platform.h
Fixes build error from android-7.1.2_r2 merge:
hardware/qcom/audio/default/hal/audio_extn/utils.c:150:25:
error: use of undeclared identifier 'HFP_ASM_RX_TX'
        pcm_device_id = HFP_ASM_RX_TX;

msm8960: Partial revert of the following
commit dd38c5fa56d4a646e2720160ba26019cef0d163b

Change-Id: I6434c31b0310be87fa7c2128da5d641898787c4f